name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Display structure of downloaded files
      run: ls -R        

    - name: easy zip
      uses: papeloto/action-zip@v1
      with:
        files: README.md
        dest: mt.zip
        recursive: true

    - uses: actions/upload-artifact@v1
      with:
        name: mt
        path: ${{ github.workspace }}/mt.zip

    - name: Display structure of downloaded files
      run: ls -R        
