name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Display structure of downloaded files
      run: ls -R        

    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        # Filename for archive
        filename: 'mt.zip'
        # Base path for archive files
        path: .
        # Working directory before zipping
        directory: .
        # List of excluded files / directories
        exclusions: '*.git* /*node_modules/* .editorconfig'
        # Tool to use for archiving (zip / tar)
        type: 'zip'

#    - uses: actions/checkout@v2

#    - uses: actions/download-artifact@v2
#      with:
#        name: release.zip
#        path: output

    - name: Display structure of downloaded files
      run: ls -R        
